services:
  - type: web
    name: expense-tracker
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri-here
      - key: JWT_SECRET
        value: your-secret-key
